### ISSUE TITLE
Hero banner.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dallas-by-metro-frontend#1]
I have some designs I am thinking off for the banner section and I would like some feedback @gpennell @ZaneBartlett1. What are y'alls preferences among these options? 

![mondrian_design](https://github.com/DartExplore/dallas-by-metro-frontend/assets/18405628/a9a5203a-b0e5-4af6-bc4f-67ab67746eef)

![skyline_design](https://github.com/DartExplore/dallas-by-metro-frontend/assets/18405628/7fea118e-b95d-46d7-9302-5669fc58cbe5)

![map_design](https://github.com/DartExplore/dallas-by-metro-frontend/assets/18405628/41ff9327-48b9-4af9-8237-7c3a9a6fcd85)

**Comment by ZaneBartlett1** [comment]
Just to confirm, how are you sourcing these images? Wondering for copy right reasons. 

I think the second is the best and most attention grabbing.....personally I really like the third one though haha. I do think we should go with the second.

**Comment by Nightwing52** [comment]
The first one was DALLE generated. The second and third one were Google searched. It looks like the second one is from Getty images and I think technically this doesn't count as commercial use because there is no financial gain on our part. For the map I could just create a diagrammatic one of the Dallas system.

My girlfriend thought the second was the best as well. I don't have any strong opinions. The third would tie in with this one design element I'll talk about tomorrow but the second is higher quality and fits in with the rest of the page better.
