### ISSUE TITLE
Create React form.

### ISSUE THREAD

**Issue by Nightwing52** [DartExplore/dallas-by-metro-frontend#11]
Use Formik to create the React form and manage its state. For starters the form should have the following inputs:
- Walk: number.
- Type: select.
- Amenity: select radio.
For now I will hardcode a few types and amenities but eventually I would like a call to get these on page load. @ZaneBartlett1 we should discuss this on the call.

**Comment by ZaneBartlett1** [comment]
I feel like this would be discussed on this issue - https://github.com/DartExplore/dallas-by-metro-backend/issues/128. This is what I want to confirm if there's any other API calls that are needed.

Again, I think we should start out with that /all endpoint so there is a way to get that for right now. Then as we have time, we can develop more specific calls.
