### ISSUE TITLE
Update Icon from default vite icon

### ISSUE THREAD

**Issue by ZaneBartlett1** [DartExplore/dallas-by-metro-frontend#54]
Dart has that little yellow pointer and google maps has a pan pin. I think we could possibly use a map pin as the icon, but that seems a little close. I thought about this for about ten minutes and thought a simple compass might be good. I'm not toooo picky on what this needs to be, especially right now, just not the default vite icon

![compass](https://github.com/DartExplore/dallas-by-metro-frontend/assets/85081861/0586b209-babf-4182-aabd-647cd4b456e3)

**Comment by Nightwing52** [comment]
I agree.
